version: "1"
project_id: suiteproxy

embedding:
  provider: openai
  base_url: http://host.docker.internal:1234/v1
  model: text-embedding-nomic-embed-text-v1.5

llm:
  enabled: true
  base_url: http://host.docker.internal:1234/v1
  model: qwen3-4b-instruct-2507
