version: "1"
project_id: suiteproxy

embedding:
  provider: openai
  base_url: http://127.0.0.1:1234/v1
  model: text-embedding-nomic-embed-text-v1.5

llm:
  enabled: true
  base_url: http://127.0.0.1:1234/v1
  model: qwen3-4b-instruct-2507
